import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const roboto = Roboto({ weight: "400", subsets: ['vietnamese'] })

export const metadata: Metadata = {
  title: 'HoiGreen\'s Portfolio',
  description: 'Generated by NextJS 14',
}

const RootLayout = ({ children, }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}

export default RootLayout
